AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AgileStories Lambda Functions

Parameters:
  OpenAIApiKey:
    Type: String
    Default: ${env:OPENAI_API_KEY}
  OpenAIOrgId:
    Type: String
    Default: ${env:OPENAI_ORG_ID}

Resources:
  AgileCoachFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ai/agents/agile_coach/
      Handler: lambda_handler.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
          OPENAI_ORG_ID: !Ref OpenAIOrgId

  SeniorDevFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ai/agents/senior_dev/
      Handler: lambda_handler.lambda_handler
      Runtime: python3.9
      Timeout: 30
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAIApiKey
          OPENAI_ORG_ID: !Ref OpenAIOrgId 